//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sav.NewFolder1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders_Services
    {
        public int Id_orders { get; set; }
        public Nullable<int> Id_services { get; set; }
        public Nullable<int> Number_orders { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Services Services { get; set; }
    }
}
