//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sav.NewFolder1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.Orders_Services = new HashSet<Orders_Services>();
        }
    
        public int Number_order { get; set; }
        public Nullable<int> Id_client { get; set; }
        public Nullable<int> Id_services { get; set; }
        public Nullable<System.DateTime> Date_orders { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public Nullable<int> Id_employee { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders_Services> Orders_Services { get; set; }
    }
}
